### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by MrMormon** [rennis250/Willow.jl#1]
Did you mean psychophysics, psychosis, or...

**Comment by rennis250** [comment]
Psychophysics is meant. It is a cross-disciplinary field, depending on psychology, neuroscience, physics, and computer science (as well as others), to describe the relation between physical stimulation and one's perception. One example is the distribution of light intensity on the retina and what one subsequently sees. Color vision research is a good specific example of visual psychophysics. The connection between physical stimulation and psychological sensation is by no means straightforward and depends on rigorous control of one's stimuli (https://en.wikipedia.org/wiki/Psychophysics). This package is an attempt to provide a new, simplified method for providing that rigorous control, in an environment that is quick to learn and quick to use.
